dependencies:
  - ipykernel
  - gdal
  - mock
  - nbconvert
  - netcdf4
  - notebook
  - numpy
  - pandoc
  - pip
  - python-dateutil
  - recommonmark
  - scipy
  - sphinx
  - sphinx_rtd_theme 
  - pip
  - pip:
    - nbsphinx
    - pythesint
    - sphinx-autobuild
